### ISSUE TITLE
TA feedback on the lesson

### ISSUE THREAD

**Issue by thierrychau** [DPI-WE/rails-migrations#1]
- should we mention here that order can matter? Maybe it's more specific to starting new projects and using references.

**Comment by ghost** [comment]
- Would it be good to add a word of caution about how manually editing the `schema.rb` file is considered bad practice? The lesson explains how this file is the authoritative source etc. and I fear some students may come up with the idea that they can bypass writing a migration and directly alter the file's content.

**Comment by heratyian** [comment]
> * Would it be good to add a word of caution about how manually editing the `schema.rb` file is considered bad practice? The lesson explains how this file is the authoritative source etc. and I fear some students may come up with the idea that they can bypass writing a migration and directly alter the file's content.

good point. the schema.rb is auto-generated based on the db when we run a migration. it shouldn't be modified. added an aside here [d1de39a](https://github.com/DPI-WE/rails-migrations/commit/d1de39af611e323053e9a6137a1075922a12107e)

**Comment by heratyian** [comment]
> * should we mention here that order can matter? Maybe it's more specific to starting new projects and using references.

I have this line "The file will be prefixed with a timestamp to ensure migrations are run in the order they were created." How do you think would best communicate that? @thierrychau

**Comment by thierrychau** [comment]
> > * should we mention here that order can matter? Maybe it's more specific to starting new projects and using references.
> 
> I have this line "The file will be prefixed with a timestamp to ensure migrations are run in the order they were created." How do you think would best communicate that? @thierrychau

I was thinking more about mentioning that if there is any relationship in the migration, the associated table needs to be created before or it can't be migrated. I think it's only true if they are using references as the type.
(e.g. to run a migration to create a characters table, the movies and the actors tables need to be created first)

**Comment by heratyian** [comment]
Ah, good point! That's part of why ideas.firstdraft.com is helpful for running migrations in order. Want to give it a shot and create a pull request? @thierrychau

**Comment by heratyian** [comment]
#2 closes
